Repository Zigje9/junction-maemo, pull requests merged in 2021-05, with the labels that each got.

#1 [FE]-set redux
  frontend/maemo-fe/package-lock.json
  frontend/maemo-fe/package.json
  frontend/maemo-fe/src/actions/type.js
  frontend/maemo-fe/src/actions/users.js
  frontend/maemo-fe/src/index.js
  frontend/maemo-fe/src/reducers/index.js
  frontend/maemo-fe/src/reducers/user.js
  frontend/maemo-fe/src/store/index.js
Labels: 💻 FE, 📒 feature

#3 [FE]-set login router
  frontend/maemo-fe/package-lock.json
  frontend/maemo-fe/package.json
  frontend/maemo-fe/src/App.js
Labels: 💻 FE, 📒 feature

#4 [FE]-create login name input
  frontend/maemo-fe/package-lock.json
  frontend/maemo-fe/package.json
  frontend/maemo-fe/src/components/LoginView/button/submitButton.jsx
  frontend/maemo-fe/src/components/LoginView/input-title/title.jsx
  frontend/maemo-fe/src/components/LoginView/input/nameInput.jsx
  frontend/maemo-fe/src/views/LoginView.jsx
Labels: 💻 FE, 📒 feature

#5 [FE]-create modal state
  frontend/maemo-fe/package-lock.json
  frontend/maemo-fe/package.json
  frontend/maemo-fe/src/components/common/modal.jsx
  frontend/maemo-fe/src/components/common/modalDiv.jsx
  frontend/maemo-fe/src/utils/random.js
  frontend/maemo-fe/src/views/LoginView.jsx
Labels: 💻 FE, 📒 feature

#7 [FE]-refactor loginView
  frontend/maemo-fe/src/components/LoginView/div/userTypeBox.jsx
  frontend/maemo-fe/src/components/LoginView/input/input.jsx
  frontend/maemo-fe/src/views/LoginView.jsx
Labels: 💎 refactoring, 💻 FE

#9 [FE]-update bookView(reservation)
  frontend/maemo-fe/src/App.js
  frontend/maemo-fe/src/components/BookView/div/bookElem.jsx
  frontend/maemo-fe/src/components/BookView/div/bookElemTop.jsx
  frontend/maemo-fe/src/components/BookView/div/container.jsx
  frontend/maemo-fe/src/views/BookView.jsx
Labels: 💻 FE, 📒 feature

#10 [FE]-refactor TimeView layout
  frontend/maemo-fe/src/components/TimeView/div/container.jsx
  frontend/maemo-fe/src/components/TimeView/input/input.jsx
  frontend/maemo-fe/src/views/TimeView.jsx
Labels: 💎 refactoring, 💻 FE

#11 [FE]-add history url
  frontend/maemo-fe/package-lock.json
  frontend/maemo-fe/package.json
  frontend/maemo-fe/src/components/MainView/button/menu.jsx
  frontend/maemo-fe/src/views/BookView.jsx
  frontend/maemo-fe/src/views/MainView.jsx
Labels: 💎 refactoring, 💻 FE, 📒 feature

#12 [FE]-login API
  frontend/maemo-fe/package-lock.json
  frontend/maemo-fe/package.json
  frontend/maemo-fe/src/api/axios.js
  frontend/maemo-fe/src/components/LoginView/button/submitButton.jsx
  frontend/maemo-fe/src/views/LoginView.jsx
Labels: 💻 FE, 📒 feature

#15 feat: signup custom models.py
  backend/maemo_rest_api/accounts/__pycache__/__init__.cpython-38.pyc
  backend/maemo_rest_api/accounts/__pycache__/admin.cpython-38.pyc
  backend/maemo_rest_api/accounts/__pycache__/apps.cpython-38.pyc
  backend/maemo_rest_api/accounts/__pycache__/managers.cpython-38.pyc
  backend/maemo_rest_api/accounts/__pycache__/models.cpython-38.pyc
  backend/maemo_rest_api/accounts/__pycache__/urls.cpython-38.pyc
  backend/maemo_rest_api/accounts/__pycache__/views.cpython-38.pyc
  backend/maemo_rest_api/accounts/admin.py
  backend/maemo_rest_api/accounts/migrations/0001_initial.py
  backend/maemo_rest_api/accounts/migrations/__pycache__/0001_initial.cpython-38.pyc
  backend/maemo_rest_api/accounts/migrations/__pycache__/__init__.cpython-38.pyc
  backend/maemo_rest_api/accounts/models.py
  backend/maemo_rest_api/accounts/urls.py
  backend/maemo_rest_api/db.sqlite3
  backend/maemo_rest_api/location/__pycache__/__init__.cpython-38.pyc
  backend/maemo_rest_api/location/__pycache__/admin.cpython-38.pyc
  backend/maemo_rest_api/location/__pycache__/apps.cpython-38.pyc
  backend/maemo_rest_api/location/__pycache__/models.cpython-38.pyc
  backend/maemo_rest_api/location/migrations/__pycache__/__init__.cpython-38.pyc
  backend/maemo_rest_api/maemo_rest_api/__pycache__/settings.cpython-38.pyc
  backend/maemo_rest_api/maemo_rest_api/__pycache__/urls.cpython-38.pyc
  backend/maemo_rest_api/maemo_rest_api/__pycache__/wsgi.cpython-38.pyc
  backend/maemo_rest_api/maemo_rest_api/settings.py
  backend/maemo_rest_api/maemo_rest_api/urls.py
  backend/maemo_rest_api/reservation/__pycache__/__init__.cpython-38.pyc
  backend/maemo_rest_api/reservation/__pycache__/admin.cpython-38.pyc
  backend/maemo_rest_api/reservation/__pycache__/apps.cpython-38.pyc
  backend/maemo_rest_api/reservation/__pycache__/models.cpython-38.pyc
  backend/maemo_rest_api/reservation/migrations/__pycache__/__init__.cpython-38.pyc
  backend/maemo_rest_api/reservation/models.py
Labels: 🔥 in progress, 🖥 BE

#13 [FE]-create container for mainView
  frontend/maemo-fe/src/assets/mrKim.svg
  frontend/maemo-fe/src/components/MainView/button/menu.jsx
  frontend/maemo-fe/src/components/MainView/div/container.jsx
  frontend/maemo-fe/src/components/MainView/div/hello.jsx
  frontend/maemo-fe/src/views/MainView.jsx
Labels: 💎 refactoring, 💻 FE, 📒 feature

#17 [FE]-positionView
  frontend/maemo-fe/public/index.html
  frontend/maemo-fe/src/views/PositionView.jsx
  frontend/maemo-fe/src/views/TimeView.jsx
Labels: 💎 refactoring, 💻 FE, 📒 feature, 🔥 in progress, 🛠 bug fix

#22 [FE]-refactor poisitionView
  frontend/maemo-fe/src/App.js
  frontend/maemo-fe/src/assets/enter.svg
  frontend/maemo-fe/src/components/PositionView/positionBottom.jsx
  frontend/maemo-fe/src/views/BookView.jsx
  frontend/maemo-fe/src/views/EnterView.jsx
  frontend/maemo-fe/src/views/LoginView.jsx
  frontend/maemo-fe/src/views/PositionView.jsx
Labels: 💎 refactoring, 💻 FE

#23 [FE]-pass states to requestView
  frontend/maemo-fe/src/App.js
  frontend/maemo-fe/src/views/PositionView.jsx
  frontend/maemo-fe/src/views/RequestView.jsx
Labels: 💻 FE, 📒 feature

#24 [FE]-refactor timeView
  frontend/maemo-fe/src/components/TimeView/button/submitButton.jsx
  frontend/maemo-fe/src/views/PositionView.jsx
  frontend/maemo-fe/src/views/TimeView.jsx
Labels: 💎 refactoring, 💻 FE, 📒 feature

#25 [FE]-refactor positionView
  frontend/maemo-fe/src/views/PositionView.jsx
Labels: 💎 refactoring, 💻 FE, 📒 feature

#27 [FE]-fix EnterView
  frontend/maemo-fe/src/App.js
  frontend/maemo-fe/src/assets/enter.svg
  frontend/maemo-fe/src/components/RequestView/button/booking.jsx
  frontend/maemo-fe/src/components/RequestView/div/container.jsx
  frontend/maemo-fe/src/components/RequestView/div/hello.jsx
  frontend/maemo-fe/src/components/RequestView/input/textarea.jsx
  frontend/maemo-fe/src/views/EnterView.jsx
  frontend/maemo-fe/src/views/RequestView.jsx
  frontend/maemo-fe/src/views/TrackingView.jsx
Labels: 💎 refactoring, 💻 FE

#26 [FE]-refactoring manageState
  frontend/maemo-fe/src/components/BookView/div/bookElem.jsx
  frontend/maemo-fe/src/views/BookView.jsx
  frontend/maemo-fe/src/views/LoginView.jsx
  frontend/maemo-fe/src/views/TimeView.jsx
Labels: 💎 refactoring, 💻 FE, 📒 feature

#28 [FE]-refactoring API, SVG files
  frontend/maemo-fe/src/App.js
  frontend/maemo-fe/src/assets/complete.svg
  frontend/maemo-fe/src/assets/main.svg
  frontend/maemo-fe/src/components/BookView/div/bookElem.jsx
  frontend/maemo-fe/src/utils/time2str.js
  frontend/maemo-fe/src/views/BookView.jsx
  frontend/maemo-fe/src/views/CompleteView.jsx
  frontend/maemo-fe/src/views/EnterView.jsx
  frontend/maemo-fe/src/views/MainView.jsx
  frontend/maemo-fe/src/views/PositionView.jsx
  frontend/maemo-fe/src/views/RequestView.jsx
  frontend/maemo-fe/src/views/TimeView.jsx
Labels: 💎 refactoring, 💡 modify, 💻 FE

#29 [FE]-feat warning layer
  frontend/maemo-fe/src/assets/closeBtn.svg
  frontend/maemo-fe/src/assets/marker.svg
  frontend/maemo-fe/src/assets/tracking.json
  frontend/maemo-fe/src/assets/warning.svg
  frontend/maemo-fe/src/components/TrackingView/layer/layer.jsx
  frontend/maemo-fe/src/views/TrackingView.jsx
Labels: 💻 FE, 📒 feature

#30 [FE]-refactor completeView
  frontend/maemo-fe/src/components/CompleteView/button/goHome.jsx
  frontend/maemo-fe/src/components/CompleteView/div/container.jsx
  frontend/maemo-fe/src/views/CompleteView.jsx
Labels: 💎 refactoring, 💻 FE

#31 [FE]-feat : finalView layout
  frontend/maemo-fe/src/App.js
  frontend/maemo-fe/src/assets/check.svg
  frontend/maemo-fe/src/components/FinalView/button/goHome.jsx
  frontend/maemo-fe/src/components/FinalView/div/container.jsx
  frontend/maemo-fe/src/views/finalView.jsx
Labels: 💎 refactoring, 💻 FE, 📒 feature

#33 [FE]-feat deviation alarm
  frontend/maemo-fe/src/assets/alarm.mp3
  frontend/maemo-fe/src/utils/trackingData/deviation/gwanghwa2jonggak.json
  frontend/maemo-fe/src/views/FinalView.jsx
  frontend/maemo-fe/src/views/TrackingView.jsx
Labels: 💻 FE

#36 [BE]-merge to main
  backend/.gitignore
  backend/maemo_rest_api/accounts/__pycache__/__init__.cpython-37.pyc
  backend/maemo_rest_api/accounts/__pycache__/admin.cpython-37.pyc
  backend/maemo_rest_api/accounts/__pycache__/apps.cpython-37.pyc
  backend/maemo_rest_api/accounts/__pycache__/managers.cpython-37.pyc
  backend/maemo_rest_api/accounts/__pycache__/models.cpython-37.pyc
  backend/maemo_rest_api/accounts/__pycache__/serializers.cpython-37.pyc
  backend/maemo_rest_api/accounts/__pycache__/urls.cpython-37.pyc
  backend/maemo_rest_api/accounts/__pycache__/views.cpython-37.pyc
  backend/maemo_rest_api/accounts/migrations/0004_alter_user_user_type.py
  backend/maemo_rest_api/accounts/migrations/0005_alter_user_protector_type.py
  backend/maemo_rest_api/accounts/migrations/__pycache__/0001_initial.cpython-37.pyc
  backend/maemo_rest_api/accounts/migrations/__pycache__/0002_remove_profile_phone.cpython-37.pyc
  backend/maemo_rest_api/accounts/migrations/__pycache__/0003_auto_20210522_0944.cpython-37.pyc
  backend/maemo_rest_api/accounts/migrations/__pycache__/__init__.cpython-37.pyc
  backend/maemo_rest_api/accounts/models.py
  backend/maemo_rest_api/accounts/serializers.py
  backend/maemo_rest_api/accounts/urls.py
  backend/maemo_rest_api/accounts/views.py
  backend/maemo_rest_api/db.sqlite3
  backend/maemo_rest_api/location/__pycache__/__init__.cpython-37.pyc
  backend/maemo_rest_api/location/__pycache__/admin.cpython-37.pyc
  backend/maemo_rest_api/location/__pycache__/apps.cpython-37.pyc
  backend/maemo_rest_api/location/__pycache__/models.cpython-37.pyc
  backend/maemo_rest_api/location/location_coordinate.py
  backend/maemo_rest_api/location/migrations/__pycache__/__init__.cpython-37.pyc
  backend/maemo_rest_api/location/notification.py
  backend/maemo_rest_api/location/views.py
  backend/maemo_rest_api/maemo_rest_api/__pycache__/__init__.cpython-37.pyc
  backend/maemo_rest_api/maemo_rest_api/__pycache__/settings.cpython-37.pyc
  backend/maemo_rest_api/maemo_rest_api/__pycache__/urls.cpython-37.pyc
  backend/maemo_rest_api/maemo_rest_api/__pycache__/wsgi.cpython-37.pyc
  backend/maemo_rest_api/maemo_rest_api/global_utils/__pycache__/custom_response.cpython-37.pyc
  backend/maemo_rest_api/maemo_rest_api/global_utils/__pycache__/jwt_token.cpython-37.pyc
  backend/maemo_rest_api/maemo_rest_api/settings.py
  backend/maemo_rest_api/maemo_rest_api/urls.py
  backend/maemo_rest_api/reservation/__pycache__/__init__.cpython-37.pyc
  backend/maemo_rest_api/reservation/__pycache__/admin.cpython-37.pyc
  backend/maemo_rest_api/reservation/__pycache__/apps.cpython-37.pyc
  backend/maemo_rest_api/reservation/__pycache__/models.cpython-37.pyc
  backend/maemo_rest_api/reservation/__pycache__/serializers.cpython-37.pyc
  backend/maemo_rest_api/reservation/__pycache__/urls.cpython-37.pyc
  backend/maemo_rest_api/reservation/__pycache__/views.cpython-37.pyc
  backend/maemo_rest_api/reservation/migrations/0004_auto_20210522_1822.py
  backend/maemo_rest_api/reservation/migrations/__pycache__/0001_initial.cpython-37.pyc
  backend/maemo_rest_api/reservation/migrations/__pycache__/0002_reservation_is_reservation_finished.cpython-37.pyc
  backend/maemo_rest_api/reservation/migrations/__pycache__/0003_auto_20210522_1131.cpython-37.pyc
  backend/maemo_rest_api/reservation/migrations/__pycache__/__init__.cpython-37.pyc
  backend/maemo_rest_api/reservation/models.py
  backend/maemo_rest_api/reservation/serializers.py
  backend/maemo_rest_api/reservation/views.py
  backend/requirements/prod.txt
Labels: 🖥 BE

#37 [FE]-remove map API key
  frontend/maemo-fe/src/App.js
  frontend/maemo-fe/src/views/CorrectTrackingView.jsx
  frontend/maemo-fe/src/views/FinalView.jsx
  frontend/maemo-fe/src/views/PositionView.jsx
Labels: 💎 refactoring, 💻 FE
